---
project_name: price-feeder

env:
  - CGO_ENABLED=1

before:
  hooks:
    - go mod download
    - scripts/extract_dependency_versions.sh github.com/cosmos/cosmos-sdk

builds:
  - main: ./
    id: "price-feeder"
    binary: price-feeder
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -tags=badgerdb ledger netgo
      - -trimpath
    ldflags:
      - -s -w
      - -X umee.commit={{.Commit}}
      - -X umee.date={{ .CommitDate }}
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ replace .Version "umee/" "umee-" }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/ojo-network/price-feeder/cmd.SDKVersion={{ .Env.GITHUB_COM_COSMOS_COSMOS_SDK_VERSION }}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: bins
    format: binary
    name_template: '{{ replace .Version "umee/" "umee-" }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

  - id: tarball
    format: tar.gz
    name_template: '{{ replace .Version "umee/" "umee-" }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: ojo-network
    name: price-feeder

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: 'SHA256SUMS-{{ replace .Version "umee/" "umee-" }}.txt'
  algorithm: sha256

changelog:
  skip: false
