config_dir = "umee-provider-config"

gas_adjustment = 1.03
provider_timeout = "1000000s"

[server]
listen_addr = "0.0.0.0:7171"
read_timeout = "20s"
verbose_cors = true
write_timeout = "20s"

[account]
address = "umee1zypqa76je7pxsdwkfah6mu9a583sju6xjavygg"
chain_id = "umee-local-testnet"
validator = "umeevaloper1zypqa76je7pxsdwkfah6mu9a583sju6xjettez"

[keyring]
backend = "test"
dir = "/Users/username/.umee"

[rpc]
grpc_endpoint = "localhost:9090"
rpc_timeout = "100ms"
tmrpc_endpoint = "http://localhost:26657"

[telemetry]
enable-hostname = true
enable-hostname-label = true
enable-service-label = true
enabled = true
global-labels = [["chain_id", "umee-local-testnet"]]
service-name = "price-feeder"
prometheus-retention-time = 100
