gas_adjustment = 1

[server]
listen_addr = "0.0.0.0:7171"
read_timeout = "20s"
verbose_cors = true
write_timeout = "20s"

[[deviation_thresholds]]
base = "USDT"
threshold = "1.5"

[[deviation_thresholds]]
base = "ATOM"
threshold = "1.5"

[[deviation_thresholds]]
base = "ETH"
threshold = "2"

[[deviation_thresholds]]
base = "BTC"
threshold = "2"

[[deviation_thresholds]]
base = "OSMO"
threshold = "2"

[[currency_pairs]]
base = "USDT"
providers = [
  "kraken",
  "coinbase",
  "binanceus",
]
quote = "USD"

[[currency_pairs]]
base = "USDC"
providers = [
  "kraken",
  "coinbase",
  "binanceus",
]
quote = "USD"

[[currency_pairs]]
base = "ATOM"
providers = [
  "okx",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "ATOM"
providers = [
  "kraken",
  "binanceus",
]
quote = "USD"

[[currency_pairs]]
base = "ETH"
providers = [
  "okx",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "ETH"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "BTC"
providers = [
  "okx",
  "gate",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "BTC"
providers = [
  "coinbase",
]
quote = "USD"

[[currency_pairs]]
base = "OSMO"
providers = [
  "bitget",
  "gate",
  "huobi",
]
quote = "USDT"

[[currency_pairs]]
base = "OSMO"
providers = [
  "osmosisv2",
]
quote = "ATOM"

[[currency_pairs]]
base = "WETH"
providers = [
  "eth-uniswap"
]

quote = "USDC"
[[currency_pairs.pair_address_providers]]
address = "0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640"
provider = "eth-uniswap"


[[currency_pairs]]
base = "UNI"
providers = [
  "eth-uniswap"
]

quote = "USDC"
[[currency_pairs.pair_address_providers]]
address = "0x1d42064fc4beb5f8aaf85f4617ae8b3b5b8bd801"
provider = "eth-uniswap"


[[currency_pairs]]
base = "WBTC"
providers = [
  "eth-uniswap"
]

quote = "USDC"
[[currency_pairs.pair_address_providers]]
address = "0xcbcdf9626bc03e24f779434178a73a0b4bad62ed"
provider = "eth-uniswap"

[account]
address = "ojo1zypqa76je7pxsdwkfah6mu9a583sju6xzthge3"
chain_id = "ojo-testnet"
validator = "ojovaloper1zypqa76je7pxsdwkfah6mu9a583sju6x6tnq6w"

[keyring]
backend = "test"
dir = "/Users/username/.ojo"

[rpc]
grpc_endpoint = "localhost:9090"
rpc_timeout = "100ms"
tmrpc_endpoint = "http://localhost:26657"

[telemetry]
enable-hostname = true
enable-hostname-label = true
enable-service-label = true
enabled = true
global-labels = [["chain_id", "ojo-testnet"]]
service-name = "price-feeder"
prometheus-retention-time = 100

[[provider_endpoints]]
name = "binance"
rest = "https://api1.binance.com"
websocket = "stream.binance.com:9443"

[[provider_endpoints]]
name = "eth-uniswap"
rest = "https://api.studio.thegraph.com/query/46403/unidexer/test41"
websocket = "not supported"
