[[deviation_thresholds]]
base = "USDT"
threshold = "1.5"

[[deviation_thresholds]]
base = "ATOM"
threshold = "1.5"

[[deviation_thresholds]]
base = "USDC"
threshold = "1.5"

[[deviation_thresholds]]
base = "ETH"
threshold = "2"

[[deviation_thresholds]]
base = "BTC"
threshold = "2"

[[deviation_thresholds]]
base = "OSMO"
threshold = "2"

[[deviation_thresholds]]
base = "DAI"
threshold = "2"

[[deviation_thresholds]]
base = "stOSMO"
threshold = "2"

[[deviation_thresholds]]
base = "stATOM"
threshold = "2"

[[deviation_thresholds]]
base = "stJUNO"
threshold = "2"

[[deviation_thresholds]]
base = "JUNO"
threshold = "2"

[[deviation_thresholds]]
base = "SCRT"
threshold = "2"

[[currency_pairs]]
base = "USDT"
providers = [
  "kraken",
  "coinbase",
  "crypto",
]
quote = "USD"

[[currency_pairs]]
base = "USDC"
providers = [
  "okx",
  "bitget",
  "kraken",
]
quote = "USDT"


[[currency_pairs]]
base = "USDC"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "ATOM"
providers = [
  "okx",
  "bitget",
  "gate",
]
quote = "USDT"

[[currency_pairs]]
base = "ATOM"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "ETH"
providers = [
  "okx",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "ETH"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "BTC"
providers = [
  "okx",
  "gate",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "BTC"
providers = [
  "coinbase",
]
quote = "USD"

[[currency_pairs]]
base = "OSMO"
providers = [
  "bitget",
  "gate",
  "huobi",
]
quote = "USDT"

[[currency_pairs]]
base = "OSMO"
providers = [
  "osmosisv2",
]
quote = "ATOM"

[[currency_pairs]]
base = "WETH"
providers = [
  "eth-uniswap"
]

quote = "USDC"
[[currency_pairs.pair_address_providers]]
address = "0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640"
provider = "eth-uniswap"

[[currency_pairs]]
base = "WBTC"
providers = [
  "eth-uniswap"
]

quote = "WETH"
[[currency_pairs.pair_address_providers]]
address = "0xcbcdf9626bc03e24f779434178a73a0b4bad62ed"
provider = "eth-uniswap"

[[currency_pairs]]
base = "CBETH"
providers = [
  "eth-uniswap"
]

quote = "WETH"
[[currency_pairs.pair_address_providers]]
address = "0x840deeef2f115cf50da625f7368c24af6fe74410"
provider = "eth-uniswap"

[[currency_pairs]]
base = "LINK"
providers = [
  "eth-uniswap"
]

quote = "WETH"
[[currency_pairs.pair_address_providers]]
address = "0xa6cc3c2531fdaa6ae1a3ca84c2855806728693e8"
provider = "eth-uniswap"

[[currency_pairs]]
base = "stATOM"
providers = [
  "osmosisv2",
  "crescent",
]
quote = "ATOM"

[[currency_pairs]]
base = "stOSMO"
providers = [
  "osmosisv2",
]
quote = "OSMO"

[[currency_pairs]]
base = "DAI"
providers = [
  "okx",
  "bitget",
  "huobi",
]
quote = "USDT"

[[currency_pairs]]
base = "DAI"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "JUNO"
providers = [
  "bitget",
  "mexc",
]
quote = "USDT"

[[currency_pairs]]
base = "JUNO"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "JUNO"
providers = [
  "osmosisv2",
]
quote = "ATOM"

[[currency_pairs]]
base = "stJUNO"
providers = [
  "osmosisv2",
]
quote = "JUNO"

[[currency_pairs]]
base = "SCRT"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "SCRT"
providers = [
  "mexc",
  "gate"
]
quote = "USDT"

[[provider_endpoints]]
name = "binance"
rest = "https://api1.binance.com"
websocket = "stream.binance.com:9443"

[[provider_endpoints]]
name = "eth-uniswap"
rest = "https://api.studio.thegraph.com/query/46403/unidexer/version/latest"
websocket = "not supported"
