[[currency_pairs]]
base = "USDT"
providers = [
  "kraken",
  "coinbase",
  "crypto",
  "gate",
]
quote = "USD"

[[currency_pairs]]
base = "ATOM"
providers = [
  "okx",
  "bitget",
  "gate",
]
quote = "USDT"

[[currency_pairs]]
base = "ATOM"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "ETH"
providers = [
  "okx",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "ETH"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "BTC"
providers = [
  "okx",
  "gate",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "BTC"
providers = [
  "coinbase",
]
quote = "USD"

[[currency_pairs]]
base = "OSMO"
providers = [
  "bitget",
  "gate",
  "huobi",
]
quote = "USDT"

[[currency_pairs]]
base = "OSMO"
providers = [
  "osmosis",
]
quote = "ATOM"

[[currency_pairs]]
base = "stATOM"
providers = [
  "osmosis",
  "crescent",
]
quote = "ATOM"

[[currency_pairs]]
base = "stOSMO"
providers = [
  "osmosis",
]
quote = "OSMO"

[[currency_pairs]]
base = "DAI"
providers = [
  "okx",
  "bitget",
  "huobi",
]
quote = "USDT"

[[currency_pairs]]
base = "DAI"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "JUNO"
providers = [
  "bitget",
  "mexc",
]
quote = "USDT"

[[currency_pairs]]
base = "JUNO"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "JUNO"
providers = [
  "osmosis",
]
quote = "ATOM"

[[currency_pairs]]
base = "stJUNO"
providers = [
  "osmosis",
]
quote = "JUNO"

[[currency_pairs]]
base = "SCRT"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "SCRT"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "SCRT"
providers = [
  "mexc",
  "gate"
]
quote = "USDT"

[[currency_pairs]]
base = "WBTC"
providers = [
  "okx",
  "bitget",
  "crypto",
]
quote = "USDT"

[[currency_pairs]]
base = "USDC"
providers = [
  "okx",
  "bitget",
  "kraken",
]
quote = "USDT"

[[currency_pairs]]
base = "USDC"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "IST"
providers = [
  "osmosis",
]
quote = "OSMO"

[[currency_pairs]]
base = "IST"
providers = [
  "crescent",
]
quote = "USDC"

[[currency_pairs]]
base = "BNB"
providers = [
  "mexc",
  "bitget",
  "okx",
]
quote = "USDT"

[[currency_pairs]]
base = "LUNA"
providers = [
  "okx",
  "gate",
  "huobi",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "DOT"
providers = [
  "kraken",
  "coinbase",
  "crypto",
]
quote = "USD"

[[currency_pairs]]
base = "DOT"
providers = [
  "gate",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "AXL"
providers = [
  "coinbase",
  "crypto",
]
quote = "USD"

[[currency_pairs]]
base = "AXL"
providers = ["osmosis"]
quote = "OSMO"

[[currency_pairs]]
base = "STARS"
providers = ["osmosis"]
quote = "ATOM"

[[currency_pairs]]
base = "STARS"
providers = ["osmosis"]
quote = "OSMO"

[[currency_pairs]]
base = "XRP"
providers = [
  "kraken",
  "coinbase",
]
quote = "USD"

[[currency_pairs]]
base = "XRP"
providers = [
  "gate",
  "mexc",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "USK"
providers = [
  "kujira",
]
quote = "USDC"

[[currency_pairs]]
base = "KUJI"
providers = [
  "kujira",
]
quote = "USDC"

[[currency_pairs]]
base = "MNTA"
providers = [
  "kujira",
]
quote = "USDC"

[[currency_pairs]]
base = "RETH"
providers = [
    "eth-uniswap",
]

quote = "WETH"
[[currency_pairs.pair_address_providers]]
address = "0xa4e0faA58465A2D369aa21B3e42d43374c6F9613"
provider = "eth-uniswap"

[[currency_pairs]]
base = "WETH"
providers = [
    "eth-uniswap"
]

quote = "USDC"
[[currency_pairs.pair_address_providers]]
address = "0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640"
provider = "eth-uniswap"

[[currency_pairs]]
base = "CBETH"
providers = [
  "eth-uniswap"
]
quote = "WETH"
[[currency_pairs.pair_address_providers]]
address = "0x840deeef2f115cf50da625f7368c24af6fe74410"
provider = "eth-uniswap"
