[[currency_pairs]]
base = "USDT"
providers = [
  "kraken",
  "coinbase",
  "crypto",
]
quote = "USD"

[[currency_pairs]]
base = "USDC"
providers = [
  "okx",
  "bitget",
  "kraken",
]
quote = "USDT"


[[currency_pairs]]
base = "USDC"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "USDC"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "ATOM"
providers = [
  "okx",
  "bitget",
  "gate",
]
quote = "USDT"

[[currency_pairs]]
base = "ATOM"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "ETH"
providers = [
  "okx",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "ETH"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "BTC"
providers = [
  "okx",
  "gate",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "BTC"
providers = [
  "coinbase",
]
quote = "USD"

[[currency_pairs]]
base = "OSMO"
providers = [
  "bitget",
  "gate",
  "huobi",
]
quote = "USDT"

[[currency_pairs]]
base = "OSMO"
providers = [
  "osmosis",
]
quote = "ATOM"

[[currency_pairs]]
base = "WETH"
providers = [
  "eth-uniswap"
]
quote = "USDC"

[[currency_pairs]]
base = "WBTC"
providers = [
  "eth-uniswap"
]
quote = "WETH"

[[currency_pairs]]
base = "CBETH"
providers = [
  "eth-uniswap"
]
quote = "WETH"

[[currency_pairs]]
base = "LINK"
providers = [
  "eth-uniswap"
]
quote = "WETH"

[[currency_pairs]]
base = "RETH"
providers = [
  "eth-uniswap",
]
quote = "WETH"

[[currency_pairs]]
base = "SFRXETH"
providers = [
  "eth-uniswap",
]
quote = "WETH"

[[currency_pairs]]
base = "WSTETH"
providers = [
  "eth-uniswap",
]
quote = "WETH"

[[currency_pairs]]
base = "stATOM"
providers = [
  "osmosis",
]
quote = "ATOM"

[[currency_pairs]]
base = "stOSMO"
providers = [
  "osmosis",
]
quote = "OSMO"

[[currency_pairs]]
base = "DAI"
providers = [
  "okx",
  "bitget",
  "huobi",
]
quote = "USDT"

[[currency_pairs]]
base = "DAI"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "JUNO"
providers = [
  "mexc",
]
quote = "USDT"

[[currency_pairs]]
base = "JUNO"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "JUNO"
providers = [
  "osmosis",
]
quote = "ATOM"

[[currency_pairs]]
base = "stJUNO"
providers = [
  "osmosis",
]
quote = "JUNO"

[[currency_pairs]]
base = "SCRT"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "SCRT"
providers = [
  "mexc",
  "gate"
]
quote = "USDT"

[[currency_pairs]]
base = "INJ"
providers = [
  "gate",
  "mexc",
]
quote = "USDT"

[[currency_pairs]]
base = "INJ"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "STINJ"
providers = [
  "astroport",
]
quote = "INJ"
