# This workflow helps with creating docker images.
# This job will only be triggered when a tag (umee/vX.X.x) is pushed
name: Release price-feeder

on:
  push:
    tags:
      - "umee/v*.*.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
          cache: true
          cache-dependency-path: go.sum
      # Parse 'umee/v*.*.*' semantic version from 'umee/v*.*.*' and save to
      # the $GITHUB_ENV environment variable.
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Release
        uses: goreleaser/goreleaser-action@v4
        with:
          # Note, we have to pin to v0.179.0 due to newer releases enforcing
          # correct semantic versioning even when '--skip-validate' is provided.
          #
          # Ref: https://github.com/goreleaser/goreleaser/pull/2503
          version: v0.179.0
          args: release --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ env.RELEASE_VERSION }}
