name: Publish Image

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: USERNAME
        password: ${{ secrets.REPO_PUSH_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/ojo-network/price-feeder-ojo
