name: Tests
on:
  pull_request:
  push:
    branches:
      - main
      - release/**

jobs:
  install-tparse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Display Go Version
        run: go version
      - uses: actions/cache@v3
        id: cache-go-tparse
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tparse-binary
      - name: Install tparse
        if: steps.cache-go-tparse.outputs.cache-hit != 'true'
        run: |
          go install github.com/mfridman/tparse@v0.11.1

  test-unit-cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/setup-go@v3
        if: env.GIT_DIFF
        with:
          go-version: 1.19
          cache: true
      - name: Test and Create Coverage Report
        if: env.GIT_DIFF
        run: |
          make test-unit-cover
      - uses: codecov/codecov-action@v3
        if: env.GIT_DIFF
        with:
          file: ./coverage.txt
          fail_ci_if_error: true

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/setup-go@v3
        if: env.GIT_DIFF
        with:
          go-version: 1.19
          cache: true
          cache-dependency-path: go.sum
      - name: Test price-feeder
        if: env.GIT_DIFF
        run: |
          make test-unit

  build-price-feeder:
    uses: ./.github/workflows/build.yml
