name: Tests
on:
  pull_request:
  push:
    branches:
      - main
      - release/**

jobs:
  install-tparse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Display Go Version
        run: go version
      - uses: actions/cache@v3
        id: cache-go-tparse
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tparse-binary
      - name: Install tparse
        if: steps.cache-go-tparse.outputs.cache-hit != 'true'
        run: |
          go install github.com/mfridman/tparse@v0.11.1

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/setup-go@v4
        if: env.GIT_DIFF
        with:
          go-version: 1.19
          cache: true
          cache-dependency-path: go.sum
      - name: Test Unit
        if: env.GIT_DIFF
        run: |
          make test-unit

  test-integration:
    runs-on: ubuntu-latest
    needs: install-tparse
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/setup-go@v4
        if: env.GIT_DIFF
        with:
          go-version: 1.19
          cache: true
      - name: Test Integration
        env:
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
        if: env.GIT_DIFF
        run: |
          make test-integration

  build-price-feeder:
    uses: ./.github/workflows/build.yml
